spring.application.name=DOSW-Library

# Spring Security
spring.security.user.name=admin
spring.security.user.password=1234

# Configuracion de PostgreSQL
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/DBLibraryLocal
spring.datasource.username=camilo
spring.datasource.password=camilo
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000


